apiVersion: v1
kind: ServiceAccount
metadata:
  name: volume-stabilization-operator
  namespace: volume-stabilization
  labels:
    app.kubernetes.io/name: volume-stabilization-operator
    app.kubernetes.io/component: serviceaccount
