/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NewPVCInfo) DeepCopyInto(out *NewPVCInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NewPVCInfo.
func (in *NewPVCInfo) DeepCopy() *NewPVCInfo {
	if in == nil {
		return nil
	}
	out := new(NewPVCInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NewPVInfo) DeepCopyInto(out *NewPVInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NewPVInfo.
func (in *NewPVInfo) DeepCopy() *NewPVInfo {
	if in == nil {
		return nil
	}
	out := new(NewPVInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OriginalPVInfo) DeepCopyInto(out *OriginalPVInfo) {
	*out = *in
	if in.AccessModes != nil {
		in, out := &in.AccessModes, &out.AccessModes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.MountOptions != nil {
		in, out := &in.MountOptions, &out.MountOptions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OriginalPVInfo.
func (in *OriginalPVInfo) DeepCopy() *OriginalPVInfo {
	if in == nil {
		return nil
	}
	out := new(OriginalPVInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourcePVCReference) DeepCopyInto(out *SourcePVCReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourcePVCReference.
func (in *SourcePVCReference) DeepCopy() *SourcePVCReference {
	if in == nil {
		return nil
	}
	out := new(SourcePVCReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetVolumeSpec) DeepCopyInto(out *TargetVolumeSpec) {
	*out = *in
	if in.StorageClassName != nil {
		in, out := &in.StorageClassName, &out.StorageClassName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetVolumeSpec.
func (in *TargetVolumeSpec) DeepCopy() *TargetVolumeSpec {
	if in == nil {
		return nil
	}
	out := new(TargetVolumeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeStabilization) DeepCopyInto(out *VolumeStabilization) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeStabilization.
func (in *VolumeStabilization) DeepCopy() *VolumeStabilization {
	if in == nil {
		return nil
	}
	out := new(VolumeStabilization)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VolumeStabilization) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeStabilizationCondition) DeepCopyInto(out *VolumeStabilizationCondition) {
	*out = *in
	if in.LastTransitionTime != nil {
		in, out := &in.LastTransitionTime, &out.LastTransitionTime
		*out = new(metav1.Time)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeStabilizationCondition.
func (in *VolumeStabilizationCondition) DeepCopy() *VolumeStabilizationCondition {
	if in == nil {
		return nil
	}
	out := new(VolumeStabilizationCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeStabilizationList) DeepCopyInto(out *VolumeStabilizationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VolumeStabilization, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeStabilizationList.
func (in *VolumeStabilizationList) DeepCopy() *VolumeStabilizationList {
	if in == nil {
		return nil
	}
	out := new(VolumeStabilizationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VolumeStabilizationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeStabilizationSpec) DeepCopyInto(out *VolumeStabilizationSpec) {
	*out = *in
	out.SourcePVC = in.SourcePVC
	in.Target.DeepCopyInto(&out.Target)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeStabilizationSpec.
func (in *VolumeStabilizationSpec) DeepCopy() *VolumeStabilizationSpec {
	if in == nil {
		return nil
	}
	out := new(VolumeStabilizationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeStabilizationStatus) DeepCopyInto(out *VolumeStabilizationStatus) {
	*out = *in
	if in.OriginalPV != nil {
		in, out := &in.OriginalPV, &out.OriginalPV
		*out = new(OriginalPVInfo)
		(*in).DeepCopyInto(*out)
	}
	if in.NewPV != nil {
		in, out := &in.NewPV, &out.NewPV
		*out = new(NewPVInfo)
		**out = **in
	}
	if in.NewPVC != nil {
		in, out := &in.NewPVC, &out.NewPVC
		*out = new(NewPVCInfo)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]VolumeStabilizationCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeStabilizationStatus.
func (in *VolumeStabilizationStatus) DeepCopy() *VolumeStabilizationStatus {
	if in == nil {
		return nil
	}
	out := new(VolumeStabilizationStatus)
	in.DeepCopyInto(out)
	return out
}
